/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dehocky1;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author admin
 */
public class quanlylophoc extends javax.swing.JFrame {

    /**
     * Creates new form quanlylophoc
     */
    public quanlylophoc() {
        initComponents();
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        showlophoc();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtablelophoc = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txttengv = new javax.swing.JTextField();
        txtmalop = new javax.swing.JTextField();
        txttenmonhoc = new javax.swing.JTextField();
        txtsiso = new javax.swing.JTextField();
        thoigianbatdau = new com.toedter.calendar.JDateChooser();
        thoigiankethuc = new com.toedter.calendar.JDateChooser();
        txtsotiet = new javax.swing.JTextField();
        btnketnoi = new javax.swing.JButton();
        btnthem = new javax.swing.JButton();
        btnsua = new javax.swing.JButton();
        btnxoa = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtsogv = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtsolopcon = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtablethongke = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        btnthongke = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("QUAN LY LOP HOC");

        jtablelophoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tengv", "malop", "tenmonhoc", "siso", "Thoigianbatdau", "Thoigiankethuc", "Sotietquydoi"
            }
        ));
        jtablelophoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtablelophocMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtablelophoc);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("tengv");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("malop");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("tenmonhoc");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("siso");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("thoigianbatdau");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("thoigiankethuc");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("sotietquydoi");

        btnketnoi.setText("ketnoi");
        btnketnoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnketnoiActionPerformed(evt);
            }
        });

        btnthem.setText("them");
        btnthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemActionPerformed(evt);
            }
        });

        btnsua.setText("sua");
        btnsua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnsuaMouseClicked(evt);
            }
        });
        btnsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuaActionPerformed(evt);
            }
        });

        btnxoa.setText("xoa");
        btnxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoaActionPerformed(evt);
            }
        });

        jLabel10.setText("sogiangvien");

        jLabel12.setText("solopcon");

        txtsolopcon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsolopconActionPerformed(evt);
            }
        });

        jtablethongke.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tengv", "Tong so lop", "Tong so tiet", "xep loai"
            }
        ));
        jScrollPane2.setViewportView(jtablethongke);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("THỐNG KÊ THÔNG TIN GIẢNG VIÊN");

        btnthongke.setText("THONG KE");
        btnthongke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthongkeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 673, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txttengv, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtmalop))
                                .addComponent(jLabel5))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtsiso, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                                    .addComponent(txttenmonhoc)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnketnoi)
                                .addGap(32, 32, 32)
                                .addComponent(btnthem)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnsua)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(thoigianbatdau, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                                    .addComponent(thoigiankethuc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtsotiet))
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnxoa)
                                .addGap(21, 21, 21))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtsogv, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(txtsolopcon, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(242, 242, 242)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnthongke)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(393, 393, 393)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(342, 342, 342)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(jLabel6)
                                .addComponent(txttengv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(thoigianbatdau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(jLabel7)
                                .addComponent(txtmalop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(thoigiankethuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8)
                            .addComponent(txttenmonhoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtsotiet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtsiso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnketnoi)
                            .addComponent(btnthem)
                            .addComponent(btnsua)
                            .addComponent(btnxoa))))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtsogv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(txtsolopcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(btnthongke)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuaActionPerformed
        // TODO add your handling code here:
        lophoc dg = new lophoc();
        String madg = (txtmalop.getText());
        if(madg!=null)
        {
            
        String tendg = txttengv.getText();
        String tenmonhoc = txttenmonhoc.getText();
        int siso= Integer.parseInt(txtsiso.getText());
        int sotietquydoi =  Integer.parseInt(txtsotiet.getText());
        
        java.sql.Date nm=(thoigianbatdau.getDate()==null)?null:new java.sql.Date(thoigianbatdau.getDate().getTime());
        java.sql.Date nt=(thoigiankethuc.getDate()==null)?null:new java.sql.Date(thoigiankethuc.getDate().getTime());
        
        dg.setTengv(tendg);
        dg.setMalop(madg);
        
        dg.setTenmonhoc(tenmonhoc);
        dg.setSiso(siso);
       
        dg.setThoigianbatdau(nm);
        dg.setThoigiankethuc(nt);
        dg.setSotietquydoi(sotietquydoi);
        
            if(JOptionPane.showConfirmDialog(null,"sua mot lop hoc", "Xác nhận", JOptionPane.YES_NO_OPTION)== JOptionPane.YES_OPTION)
            {
                if(lophocDAO.update(dg,madg)>0)
                   {
                       JOptionPane.showMessageDialog(null, "sua thanh cong"); 
                   }
                   else 
                   {
                        JOptionPane.showMessageDialog(null, "sua that bai"); 
                   }
            }
        }
        else
        {
              JOptionPane.showMessageDialog(null, "khong ton tai doc gia"); 
        }
         showlophoc();
    }//GEN-LAST:event_btnsuaActionPerformed

    private void btnketnoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnketnoiActionPerformed
        // TODO add your handling code here:
       // txttongsolop.setText(String.valueOf(lophocDAO.solop()));
        txtsogv.setText(String.valueOf(lophocDAO.sogiangvien()));
        //txsolopkt.setText(String.valueOf(lophocDAO.solopkethuc()));
        txtsolopcon.setText(String.valueOf(lophocDAO.solopcon()));
        //txtlopmin.setText(String.valueOf(lophocDAO.lopSiSoMin()));
        
       
    }//GEN-LAST:event_btnketnoiActionPerformed

    private void btnthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemActionPerformed
        // TODO add your handling code here:
        lophoc dg = new lophoc();
        String malop = (txtmalop.getText());
        if(malop!=null)
        {
            
            String tengv = txttengv.getText();
            String tenmonhoc = txttenmonhoc.getText();
            int siso = Integer.parseInt(txtsiso.getText());
            int sotietquydoi = Integer.parseInt(txtsotiet.getText());
            java.sql.Date nm=(thoigianbatdau.getDate()==null)?null:new java.sql.Date(thoigianbatdau.getDate().getTime());
            java.sql.Date nt=(thoigiankethuc.getDate()==null)?null:new java.sql.Date(thoigiankethuc.getDate().getTime());

            dg.setMalop(malop);
            dg.setTengv(tengv);
           
            dg.setTenmonhoc(tenmonhoc);
            dg.setSiso(siso);
            dg.setSotietquydoi(sotietquydoi);
            dg.setThoigianbatdau(nm);
            dg.setThoigiankethuc(nt);


                if(JOptionPane.showConfirmDialog(null,"them mot lop", "Xác nhận", JOptionPane.YES_NO_OPTION)== JOptionPane.YES_OPTION)
                {
                    if(lophocDAO.them(dg)>0)
                       {
                           JOptionPane.showMessageDialog(null, "Thêm thanh cong"); 
                       }
                       else 
                       {
                            JOptionPane.showMessageDialog(null, "Thêm that bai"); 
                       }
                }
        }
         showlophoc();
    }//GEN-LAST:event_btnthemActionPerformed

    private void btnsuaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsuaMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_btnsuaMouseClicked

    private void jtablelophocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtablelophocMouseClicked
        // TODO add your handling code here:
        int selectedrow = jtablelophoc.getSelectedRow();
   
        DefaultTableModel model = (DefaultTableModel)jtablelophoc.getModel();
        txttengv.setText(((String)model.getValueAt(selectedrow, 0).toString()));
        txtmalop.setText(model.getValueAt(selectedrow, 1).toString());
        txttenmonhoc.setText(model.getValueAt(selectedrow, 2).toString());
        txtsiso.setText(model.getValueAt(selectedrow, 3).toString());
        txtsotiet.setText(String.valueOf(model.getValueAt(selectedrow, 6)));
        
        try {
            thoigianbatdau.setDate(new SimpleDateFormat("yyyy-MM-dd").parse((String)model.getValueAt(selectedrow, 4).toString()));
            thoigiankethuc.setDate(new SimpleDateFormat("yyyy-MM-dd").parse((String)model.getValueAt(selectedrow, 5).toString()));
        } catch (ParseException ex) {
            Logger.getLogger(quanlylophoc.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jtablelophocMouseClicked

    private void btnxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoaActionPerformed
        // TODO add your handling code here:
        String malop= (txtmalop.getText());
        String tengv=txttengv.getText();
        if(malop!=null && tengv!=null)
        {
           
            if(JOptionPane.showConfirmDialog(null,"xoa 1 lop hoc ?", "Xác nhận", JOptionPane.YES_NO_OPTION)== JOptionPane.YES_OPTION)
                if(lophocDAO.del(malop,tengv)>0)
                {
                    //btnKetNoi.doClick();
                    JOptionPane.showMessageDialog(null, "xoa thành công"); 
                    
                }
                else 
                {
                     JOptionPane.showMessageDialog(null, "xoa that bai"); 
                }
            showlophoc(); 
        }
    }//GEN-LAST:event_btnxoaActionPerformed

    private void btnthongkeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthongkeActionPerformed
        // TODO add your handling code here:
        //lophoc pc =new lophoc();
        showthongke();
      
    }//GEN-LAST:event_btnthongkeActionPerformed

    private void txtsolopconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsolopconActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsolopconActionPerformed

    public void showthongke( )
    {
       
        List<lophoc> list=  lophocDAO.thongke();
        DefaultTableModel model = (DefaultTableModel) jtablethongke.getModel();
        for(int i=0;i<list.size();i++)
        {
                lophoc pc=list.get(i);
                String col2=pc.getTengv()==null?"":pc.getTengv();
                String col1=pc.getMalop()==null?"":pc.getMalop();
                String col3 =String.valueOf(pc.getSotietquydoi());
                String col4=pc.getSotietquydoi()>=135?"Đạt":"Không Đạt";
                String[] l= {col1,col2,col3,col4};
                model.addRow(l);
                
        }
    }
    public void showlophoc()
    {
        List<lophoc> list= lophocDAO.dsPhanCong();
        DefaultTableModel model = (DefaultTableModel) jtablelophoc.getModel();
        model.setRowCount(0);
        Object[] row = new Object[7];
        for (int i = 0; i < list.size(); i++) {
            row[1] = list.get(i).getMalop();
            row[0] = list.get(i).getTengv();
            row[2] = list.get(i).getTenmonhoc();
            row[3] = list.get(i).getSiso();
            row[4] = list.get(i).getThoigianbatdau();
            row[5] = list.get(i).getThoigiankethuc();
            row[6] = list.get(i).getSotietquydoi();
           
            model.addRow(row);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(quanlylophoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(quanlylophoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(quanlylophoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(quanlylophoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new quanlylophoc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnketnoi;
    private javax.swing.JButton btnsua;
    private javax.swing.JButton btnthem;
    private javax.swing.JButton btnthongke;
    private javax.swing.JButton btnxoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jtablelophoc;
    private javax.swing.JTable jtablethongke;
    private com.toedter.calendar.JDateChooser thoigianbatdau;
    private com.toedter.calendar.JDateChooser thoigiankethuc;
    private javax.swing.JTextField txtmalop;
    private javax.swing.JTextField txtsiso;
    private javax.swing.JTextField txtsogv;
    private javax.swing.JTextField txtsolopcon;
    private javax.swing.JTextField txtsotiet;
    private javax.swing.JTextField txttengv;
    private javax.swing.JTextField txttenmonhoc;
    // End of variables declaration//GEN-END:variables
}
